### ISSUE TITLE
不能动态更新theme吗？

### ISSUE THREAD

**Issue by zhump** [hustcc/echarts-for-react#24]
如题

**Comment by hustcc** [comment]
这是一个问题，我抽时间解决这个问题，感谢反馈~

**Comment by runninghair08** [comment]
This would be awesome! Right now I have to destroy the chart and recreate it. Unfortunately after doing so I have to set all my options again, since they are being changed dynamically by the user as well. If we could set it dynamically that would make it so much easier! 

Also, great work on this js library, it is seriously awesome. :)

**Comment by hustcc** [comment]
这个需要 echarts 先支持这个特性，如果那边新增该特性，这边立即会加入支持。
