### ISSUE TITLE
No auto-resizing when shrinking window width

### ISSUE THREAD

**Issue by CitiVince** [hustcc/echarts-for-react#268]
I'm just getting started with echarts-for-react. 

At first load, it will neatly fit any window size. When starting with a small window, it also adjusts to the window size. However, when I shrink the window size, the element keeps its width until I refresh the page. 

What am I doing wrong? Thanks for any advise!

**Comment by l3ku** [comment]
I'm struggling with a similar issue myself, too. I found a [Stack Overflow article](https://stackoverflow.com/questions/27800171/echarts-how-to-use-the-resize-event-of-the-window) that describes using the `window.resize` event bound to a function that resizes the plot, but I have not found out a neat way to use it with `echarts-for-react`. Might use the `echarts` package directly because of the limited support of this package.

**Comment by hustcc** [comment]
which  version are you use？

the lastest version fixed this bug after use `size-sensor`.
