### ISSUE TITLE
splitLine  function Did not work 

### ISSUE THREAD

**Issue by Marszht** [hustcc/echarts-for-react#385]
`option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu' ],
    	splitLine: {
		show: true,
		interval:  (index, value) => {
			console.log(index, value)
			return index === 2;
	    	},
	       // 	interval: 0,
	    	lineStyle: {
			color: '#FC5850',
			type: 'dashed'
		    }
	   },
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80],
        type: 'bar',
        showBackground: true,
        backgroundStyle: {
            color: 'rgba(220, 220, 220, 0.8)'
        }
    }]
};
`
[example](https://echarts.apache.org/examples/zh/editor.html?c=bar-background);

except： the splitLine function can work right

**Comment by NeroMorto** [comment]
@Marszht What are you trying to do?
Do you want show split line after each 2-nd index?

**Comment by Marszht** [comment]
> @Marszht What are you trying to do?
> Do you want show split line after each 2-nd index?

no, 

> @Marszht What are you trying to do?
> Do you want show split line after each 2-nd index?

no, i want to show split line when index equal  2

**Comment by NeroMorto** [comment]
I see, I think it is impossible for now as I know. First of all because this function setups an interval, not a data where display or not display split lines exactly.
But this is not problem of this wrapper (I mean [hustcc/echarts-for-react](https://github.com/hustcc/echarts-for-react)).
You can try to ask this question in [apache/incubator-echarts](https://github.com/apache/incubator-echarts/issues) for more qualified answer) But try to provide more information about what are you trying to do)

I've tryed to solve same problem with labels on 'time' xAxis, but there worse - interval options available only for category axis.
I saw that it may be improved in the next major relese (5.0) which is currently in beta.

**Comment by hustcc** [comment]
https://github.com/hustcc/echarts-for-react/issues/388
