### ISSUE TITLE
Linear Gradient Area Style

### ISSUE THREAD

**Issue by churchill1973** [hustcc/echarts-for-react#420]
Hi lovely people!

First, many thanks for your module, which, basically, makes easier our lives.
I was making a time series chart and I was wondering how could I use **Linear gradient** for filling the area under the curve.
I know that using **Echarts** I could write:
` areaStyle: {
      color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
          offset: 0,
          color: 'rgb(255, 158, 68)'
      }, {
          offset: 1,
          color: 'rgb(255, 70, 131)'
      }])
  },`
But in **echarts-for-react** I have no idea how to call graphic.LinearGradient.

Many thanks in advance.

**Comment by hustcc** [comment]
Same with echarts, just pass the option into the component props.

**Comment by Linloir** [comment]
Hi there, I'm encountering the same problem.
I'm trying to make a **gradient** filling of the area, and it requires for the `new echarts.graphic.LinearGradient` call. However, I have no idea how I can call that constructor within echarts-for-react.
I understand that I'm able to pass the options to component props after I'm done with this function call, but the problem here is the function call has to be made inside the `option` object to create a linear gradient filling.

**Comment by Linloir** [comment]
> Hi there, I'm encountering the same problem. I'm trying to make a **gradient** filling of the area, and it requires for the `new echarts.graphic.LinearGradient` call. However, I have no idea how I can call that constructor within echarts-for-react. I understand that I'm able to pass the options to component props after I'm done with this function call, but the problem here is the function call has to be made inside the `option` object to create a linear gradient filling.

Apologize for my abruptness, after some research on this topic I found out the function call can be  replaced by a color object described in the [documentation](https://echarts.apache.org/en/option.html#color) of echarts.

Hope this will help others who ran into this same problem.
